services:
  app:
    build: .
    ports:
      - "8082:8082"
    env_file:
      - ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - ./.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: