"""rename table

Revision ID: 10d785d3dcc6
Revises: ae19a3b64ba9
Create Date: 2025-09-06 11:56:24.892359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d785d3dcc6'
down_revision: Union[str, Sequence[str], None] = 'ae19a3b64ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theatre_name', sa.String(length=255), nullable=False),
    sa.Column('performance_name', sa.String(length=255), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_data'), 'tickets', ['date'], unique=False)
    op.create_index(op.f('ix_tickets_performance_name'), 'tickets', ['performance_name'], unique=False)
    op.create_index(op.f('ix_tickets_theatre_name'), 'tickets', ['theatre_name'], unique=False)
    op.create_index(op.f('ix_tickets_tickets_count'), 'tickets', ['tickets_count'], unique=False)
    op.drop_index(op.f('ix_users_data'), table_name='users')
    op.drop_index(op.f('ix_users_performance_name'), table_name='users')
    op.drop_index(op.f('ix_users_theatre_name'), table_name='users')
    op.drop_index(op.f('ix_users_tickets_count'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('theatre_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('performance_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tickets_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_tickets_count'), 'users', ['tickets_count'], unique=False)
    op.create_index(op.f('ix_users_theatre_name'), 'users', ['theatre_name'], unique=False)
    op.create_index(op.f('ix_users_performance_name'), 'users', ['performance_name'], unique=False)
    op.create_index(op.f('ix_users_data'), 'users', ['date'], unique=False)
    op.drop_index(op.f('ix_tickets_tickets_count'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_theatre_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_performance_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_data'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
