"""Intial migration

Revision ID: ae19a3b64ba9
Revises: 
Create Date: 2025-09-05 21:34:53.626892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae19a3b64ba9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('theatre_name', sa.String(length=255), nullable=False),
    sa.Column('performance_name', sa.String(length=255), nullable=False),
    sa.Column('tickets_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_data'), 'users', ['data'], unique=False)
    op.create_index(op.f('ix_users_performance_name'), 'users', ['performance_name'], unique=False)
    op.create_index(op.f('ix_users_theatre_name'), 'users', ['theatre_name'], unique=False)
    op.create_index(op.f('ix_users_tickets_count'), 'users', ['tickets_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tickets_count'), table_name='users')
    op.drop_index(op.f('ix_users_theatre_name'), table_name='users')
    op.drop_index(op.f('ix_users_performance_name'), table_name='users')
    op.drop_index(op.f('ix_users_data'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
