"""Исправлена опечатка в таблице tickets (data -> date)

Revision ID: e206c6abdeb6
Revises: e53c6d3dc5c5
Create Date: 2025-09-14 17:31:17.192864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e206c6abdeb6'
down_revision: Union[str, Sequence[str], None] = 'e53c6d3dc5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_tickets_data'), table_name='tickets')
    op.create_index(op.f('ix_tickets_date'), 'tickets', ['date'], unique=False)
    op.drop_column('tickets', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tickets_date'), table_name='tickets')
    op.create_index(op.f('ix_tickets_data'), 'tickets', ['data'], unique=False)
    op.drop_column('tickets', 'date')
    # ### end Alembic commands ###
